trigger:
  branches:
    include:
       - main

steps:
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
 # inputs:
 #terraformVersion: '1.4.6' 


 
- task: TerraformTaskV2@2
  inputs:
    provider: 'azurerm'
    command: 'init'
    backendServiceArm: 'test-devops'
    backendAzureRmResourceGroupName: 'KE-DevOps-LandingZone'
    backendAzureRmStorageAccountName: 'testwesteurope123'
    backendAzureRmContainerName: 'test-dev'
    backendAzureRmKey: '77Q4LUB5o9wRdbPYDt+0kGZP+L8Sj9E/FNXg7lZBQS5z3mLod5cyan4wA19CR1SmlqIRUFQfhuQrPVaGzNhjGw==''

- task: TerraformTaskV2@2
 inputs:
 provider: 'azurerm'
 command: 'plan'
 environmentServiceNameAzureRM: 'test-devops'



- task: TerraformTaskV2@2
 inputs:
 provider: 'azurerm'
 command: 'apply'
 environmentServiceNameAzureRM: 'test-devops'